# Generated by Django 2.1.1 on 2018-11-04 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('passwd', models.CharField(max_length=20)),
                ('info', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('cover', models.ImageField(upload_to='')),
                ('info', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('isDelete', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Correct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('info', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('buyer', models.CharField(max_length=20)),
                ('brate', models.DecimalField(decimal_places=1, max_digits=1)),
                ('srate', models.DecimalField(decimal_places=1, max_digits=1)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('isFinish', models.BooleanField(default=False)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_id', to='bookdeal.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('info', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Rlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=500)),
                ('dept', models.CharField(max_length=50)),
                ('grade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('passwd', models.CharField(max_length=20)),
                ('credit', models.DecimalField(decimal_places=1, default=5.0, max_digits=2)),
                ('info', models.CharField(blank=True, max_length=50)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Normal',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bookdeal.User')),
                ('dept', models.CharField(blank=True, max_length=20)),
                ('grade', models.IntegerField(blank=True)),
            ],
            bases=('bookdeal.user',),
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bookdeal.User')),
                ('sale', models.IntegerField()),
            ],
            bases=('bookdeal.user',),
        ),
        migrations.AddField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to='bookdeal.User'),
        ),
        migrations.AddField(
            model_name='report',
            name='trans',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trans', to='bookdeal.Order'),
        ),
        migrations.AddField(
            model_name='correct',
            name='correcter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correcter', to='bookdeal.User'),
        ),
        migrations.AddField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='bookdeal.User'),
        ),
    ]
